services:
  - type: web
    name: video-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r src/requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
