POST http://localhost:8000/transcribe/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test_1.mp3"
Content-Type: audio/mpeg

< /home/meihan/Downloads/test_2.mp3
--boundary--
